# Generated by Django 6.0.7 on 2026-09-10 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_nic_user_pin_code_user_pin_enabled'),
        ('restaurants', '0004_restaurant_supports_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='delivery_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_staff', to='restaurants.restaurant'),
        ),
    ]
