# Generated by Django 6.0.7 on 2026-08-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_menuitemvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='supports_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='supports_dine_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='supports_takeaway',
            field=models.BooleanField(default=True),
        ),
    ]
