# Generated by Django 6.0.7 on 2026-08-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_supports_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='supports_reservations',
            field=models.BooleanField(default=True),
        ),
    ]
