# Generated by Django 6.0.7 on 2026-08-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_tablesession_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAYMENT_PENDING', 'Payment Pending Confirmation'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
