# Generated by Django 6.0.7 on 2026-09-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_promotion_order_subtotal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
