# Generated by Django 6.0.7 on 2026-09-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_delivery_latitude_order_delivery_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
