# Generated by Django 6.0.7 on 2026-09-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_assigned_delivery_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
