# Generated by Django 6.0.7 on 2026-09-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_delivery_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider_current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
