# Generated by Django 6.0.7 on 2026-08-21 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_table_number_reservation_table_session'),
        ('restaurants', '0002_menuitemvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_order_items', to='restaurants.menuitemvariant'),
        ),
        migrations.AddField(
            model_name='preorderitem',
            name='variant_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
